apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnTaskDefinition
metadata:
  name: kafka-check
spec:
  function:
    httpRef:
      url: https://raw.githubusercontent.com/henrikrexed/sre-workshop/master/keptn/script/dns_istio.ts
    parameters:
      map:
        host: opentelemetry-demo-kafka
        istio: true