apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-demo
bases:
  - ../keptn-predeployment_adservice.yaml
  - ../keptn-predeployment_cartservice.yaml
  - ../keptn-predeployment_checkoutservice.yaml
  - ../keptn-predeployment_currency.yaml
  - ../keptn-predeployment_featureflag.yaml
  - ../keptn-predeployment_frontend.yaml
  - ../keptn-predeployment_kafka.yaml
  - ../keptn-predeployment_paymentservice.yaml
  - ../keptn-predeployment_postgres.yaml
  - ../keptn-predeployment_productcatalogserice.yaml
  - ../keptn-predeployment_recommendation.yaml
  - ../keptn-predeployment_redis.yaml
  - ../keptn-predeployment_shipping.yaml

patchesStrategicMerge:
  - application.yaml
  - K8sdemo.yaml